# Pyrefly header
[tool.pyrefly]

# Configuring type checks and import sources
project-includes = [
    "**/*.py*"
]
search-path = [
    "src"
]

# Configuring Python environment
python-version = ">=3.14"

# Build system header
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "econ_automation"
version = "0.3.0"
description = "A collection of workflow automation scripts for the Stokes & Associates Econ department."
authors = [
    {name = "Eric Bussey", email = "ebussey@stokes-associates.com"}
]
maintainers = [
    {name = "Eric Bussey", email = "ebussey@stokes-associates.com"}
]
# Last updated: 5/29/2026
dependencies = [
    "altgraph==0.17.5",
    "annotated-types==0.7.0",
    "appscript==1.4.0",
    "certifi==2026.4.22",
    "charset-normalizer==3.4.7",
    "docxtpl==0.20.2",
    "et_xmlfile==2.0.0",
    "idna==3.15",
    "Jinja2==3.1.6",
    "lxml==6.1.0",
    "macholib==1.16.4",
    "MarkupSafe==3.0.3",
    "numpy==2.4.4",
    "openpyxl==3.1.5",
    "packaging==26.2",
    "pandas==3.0.2",
    "pillow==12.2.0",
    "psutil==7.2.2",
    "pydantic==2.13.3",
    "pydantic_core==2.46.3",
    "pyinstaller==6.20.0",
    "pyinstaller-hooks-contrib==2026.5",
    "pypdf==6.10.2",
    "PySide6==6.11.1",
    "PySide6_Addons==6.11.1",
    "PySide6_Essentials==6.11.1",
    "python-dateutil==2.9.0.post0",
    "python-docx==1.2.0",
    "python-json-logger==4.1.0",
    "PyYAML==6.0.3",
    "requests==2.34.1",
    "setuptools==82.0.1",
    "shiboken6==6.11.1",
    "six==1.17.0",
    "types-openpyxl==3.1.5.20260408",
    "types-python-dateutil==2.9.0.20260408",
    "types-PyYAML==6.0.12.20260408",
    "types-requests==2.33.0.20260513",
    "typing-inspection==0.4.2",
    "typing_extensions==4.15.0",
    "tzdata==2026.2",
    "urllib3==2.7.0",
    "xlwings==0.35.1",
]