; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "EconAutomation"
#define MyAppVersion "0.4.1"
#define MyAppPublisher "Eric Bussey"
#define MyAppURL "https://github.com/ebusseyst/EconAutomation-REP/"
#define MyAppExeName "EconAutomation.exe"
#define MyAppGuid "6F54F296-0E19-4255-B6D0-C309453DB77C"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{{#MyAppGuid}}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer.
;SetupArchitecture=x64
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
OutputDir=C:\Users\EricBussey\GitHub\EconAutomation-REP\EconAutomation\innosetup
OutputBaseFilename=EconAutomation
SetupIconFile=C:\Users\EricBussey\GitHub\EconAutomation-REP\EconAutomation\innosetup\bolt_boost_icon.ico
SolidCompression=yes
WizardStyle=modern dynamic
CloseApplications=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\EricBussey\GitHub\EconAutomation-REP\EconAutomation\dist\EconAutomation\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\EricBussey\GitHub\EconAutomation-REP\EconAutomation\dist\EconAutomation\_internal\*"; DestDir: "{app}\_internal"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
procedure CurStepChanged(CurStep: TSetupStep);
var
  uninstallStr: String;
  resultCode: Integer;
begin
  if CurStep <> ssInstall then Exit;

  uninstallStr := '';

  // Check user-mode install first (matches PrivilegesRequired=lowest)
  if not RegQueryStringValue(HKCU,
      'Software\Microsoft\Windows\CurrentVersion\Uninstall\{{#MyAppGuid}}_is1',
      'UninstallString', uninstallStr) then
  begin
    // Fall back to machine-wide install
    RegQueryStringValue(HKLM,
        'Software\Microsoft\Windows\CurrentVersion\Uninstall\{{#MyAppGuid}}_is1',
        'UninstallString', uninstallStr);
  end;

  if uninstallStr <> '' then
    Exec(RemoveQuotes(uninstallStr), '/SILENT /SUPPRESSMSGBOXES', '', SW_HIDE,
         ewWaitUntilTerminated, resultCode);
end;

